site_name: DSX AI Trading - Documentaci贸n
site_description: Documentaci贸n oficial del ecosistema de trading DSX AI.
site_author: DSX AI Trading

theme:
  name: material
  language: es
  palette:
    scheme: default 
    primary: 'blue grey'
    accent: 'cyan'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - static-i18n:
      default_language: es
      languages:
        - es
        - en
      nav_translations:
        en:
          'Introducci贸n': 'Introduction'

nav:
  - 'Introducci贸n': 'index.md'
